package it.unibo.PokeRogue.scene;

public enum SceneFightGraphicEnum {

    FIGHT_BUTTON(1),        
    POKEMON_BUTTON(2),      
    BALL_BUTTON(3),         
    RUN_BUTTON(4),          

    // bottoni mosse pokemon
    MOVE_BUTTON_1(100),
    MOVE_BUTTON_3(101),
    MOVE_BUTTON_2(102),
    MOVE_BUTTON_4(103),

    // bottoni rappresentanti pokemon per il cambio
    CHANGE_POKEMON_1(200),
    CHANGE_POKEMON_2(201),
    CHANGE_POKEMON_3(202),
    CHANGE_POKEMON_4(203),
    CHANGE_POKEMON_5(204),
    CHANGE_POKEMON_BACK(205),

    // bottoni per selezione della pokeball da lanciare
    POKEBALL_BUTTON(300),
    MEGABALL_BUTTON(301),
    ULTRABALL_BUTTON(302),
    MASTERBALL_BUTTON(303),
    CANCEL_BUTTON(304),
    
    BACKGROUND(400),
    DETAILS_CONTAINER_BOX(401), //nop
    DETAILS_CONTAINER_TEXT(402),
    FIGHT_BUTTON_TEXT(403),
    BALL_BUTTON_TEXT(404),
    POKEMON_BUTTON_TEXT(405),
    RUN_BUTTON_TEXT(406),
    MY_POKEMON_SPRITE(407),
    MY_POKEMON_STATS_BOX(408),
    MY_POKEMON_NAME_TEXT(409),
    MY_POKEMON_LEVEL_TEXT(410),
    MY_POKEMON_ACTUAL_LIFE_TEXT(411),
    MY_POKEMON_MAX_LIFE_TEXT(412), //nop
    MY_POKEMON_LIFE_BOX(413),
    MY_POKEMON_ACTUAL_EXP_TEXT(414),
    MY_POKEMON_NEXT_LEVEL_EXP_TEXT(415),
    ENEMY_POKEMON_SPRITE(416), 
    ENEMY_POKEMON_STATS_BOX(417),
    ENEMY_POKEMON_NAME_TEXT(418),
    ENEMY_POKEMON_LEVEL_TEXT(419),
    ENEMY_POKEMON_ACTUAL_LIFE_TEXT(420),
    ENEMY_POKEMON_MAX_LIFE_TEXT(421), //nop
    ENEMY_POKEMON_LIFE_BOX(422),

    MOVES_DETAIL_CONTAINER_BOX(423), //nop
    MOVE_1_TEXT(424),
    MOVE_2_TEXT(425),
    MOVE_3_TEXT(426),
    MOVE_4_TEXT(427),
    MOVE_TYPE_TEXT(428),
    MOVE_TYPE_VALUE_TEXT(429), //nop
    MOVE_PP_TEXT(430),
    MOVE_PP_VALUE_TEXT(431), //nop
    MOVE_PP_VALUE_MAX_TEXT(432), //nop
    MOVE_POWER_TEXT(433),
    MOVE_POWER_VALUE_TEXT(434), //nop

    POKEMON_1_STATS_BOX(435),
    POKEMON_1_NAME_TEXT(436),
    POKEMON_1_LEVEL_TEXT(437),
    POKEMON_1_ACTUAL_LIFE_TEXT(438),
    POKEMON_1_MAX_LIFE_TEXT(439),
    POKEMON_1_LIFE_BOX(440),
    POKEMON_2_STATS_BOX(441),
    POKEMON_2_NAME_TEXT(442),
    POKEMON_2_LEVEL_TEXT(443),
    POKEMON_2_ACTUAL_LIFE_TEXT(444),
    POKEMON_2_MAX_LIFE_TEXT(445),
    POKEMON_2_LIFE_BOX(446),
    POKEMON_3_STATS_BOX(447),
    POKEMON_3_NAME_TEXT(448),
    POKEMON_3_LEVEL_TEXT(449),
    POKEMON_3_ACTUAL_LIFE_TEXT(450),
    POKEMON_3_MAX_LIFE_TEXT(451),
    POKEMON_3_LIFE_BOX(452),
    POKEMON_4_STATS_BOX(453),
    POKEMON_4_NAME_TEXT(454),
    POKEMON_4_LEVEL_TEXT(455),
    POKEMON_4_ACTUAL_LIFE_TEXT(456),
    POKEMON_4_MAX_LIFE_TEXT(457),
    POKEMON_4_LIFE_BOX(458),
    POKEMON_5_STATS_BOX(459),
    POKEMON_5_NAME_TEXT(460),
    POKEMON_5_LEVEL_TEXT(461),
    POKEMON_5_ACTUAL_LIFE_TEXT(462),
    POKEMON_5_MAX_LIFE_TEXT(463),
    POKEMON_5_LIFE_BOX(464),
    POKEMON_6_STATS_BOX(465),
    POKEMON_6_NAME_TEXT(466),
    POKEMON_6_LEVEL_TEXT(467),
    POKEMON_6_ACTUAL_LIFE_TEXT(468),
    POKEMON_6_MAX_LIFE_TEXT(469),
    POKEMON_6_LIFE_BOX(470),

    BALL_BOX(471),
    POKEBALL_TEXT(472),
    POKEBALL_NUMBER_TEXT(473),
    MEGABALL_TEXT(474),
    MEGABALL_NUMBER_TEXT(475),
    ULTRABALL_TEXT(476),
    ULTRABALL_NUMBER_TEXT(477),
    MASTERBALL_TEXT(478),
    MASTERBALL_NUMBER_TEXT(479),
    CANCEL_TEXT(480);

    private final int code;

    SceneFightGraphicEnum(int code) {
        this.code = code;
    }

    public int value() {
        return code;
    }
}
