package it.unibo.PokeRogue.scene.shop.enums;

public enum SceneShopEnum {
    

    BACKGROUND(100),

    PLAYER_MONEY_BOX(101),
    PLAYER_MONEY_TEXT(102),

    REROL_TEXT(104),

    ITEM_DESCRIPTION_TEXT(107),

    PRICY_ITEM_1_PRICE_TEXT(118),
    PRICY_ITEM_2_PRICE_TEXT(120),
    PRICY_ITEM_3_PRICE_TEXT(122),

    FREE_ITEM_1_NAME_TEXT(123),
    FREE_ITEM_2_NAME_TEXT(124),
    FREE_ITEM_3_NAME_TEXT(125),

    PRICY_ITEM_1_NAME_TEXT(126),
    PRICY_ITEM_2_NAME_TEXT(127),
    PRICY_ITEM_3_NAME_TEXT(128),

    TEAM_TEXT(129),
    CHANGE_POKEMON_BACK_TEXT(130),

    POKEMON_1_NAME_TEXT(436),
    POKEMON_1_LIFE_TEXT(438),

    POKEMON_2_NAME_TEXT(442),
    POKEMON_2_LIFE_TEXT(444),

    POKEMON_3_NAME_TEXT(448),
    POKEMON_3_LIFE_TEXT(450),

    POKEMON_4_NAME_TEXT(454),
    POKEMON_4_LIFE_TEXT(456),

    POKEMON_5_NAME_TEXT(460),
    POKEMON_5_LIFE_TEXT(462),

    POKEMON_6_NAME_TEXT(466),
    POKEMON_6_LIFE_TEXT(468);

    private final int code;

    SceneShopEnum(int code) {
        this.code = code;
    }

    public int value() {
        return code;
    }
}
